### ISSUE TITLE
Can I use your script with Google Streetview ?

### ISSUE THREAD

**Issue by SaulBurgos** [bramus/photoshop-google-maps-tile-cutter#13]
Hi your script is great I have been using it in some projects. But now I want use it with Google custom streetview but is not working correctly.

Example with custom map
http://imgur.com/Ra90Uzz

Example with streetview
http://imgur.com/fpTtN9o

Do I miss an option ? Am I doing something wrong ? or The script is not for this purpose ?

**Comment by bramus** [comment]
Hi @SaulBurgos,

This tilecutter script is used to cut up a bit map image for use with the regular Google Maps. Streetview is an entirely different thing, and thus outside of the scope of this project.

Regards,
Bramus.
