### ISSUE TITLE
overlay

### ISSUE THREAD

**Issue by timmccloskey** [bramus/photoshop-google-maps-tile-cutter#14]
Great work. Any thoughts of how to make tiles and use them as tiles on a specific location? I've been searching for a few days trying to find something that will take a photoshop document, create map tiles, and then have them organized to specific zoom levels and location (without all the math). Yours is the closest open source I've found.

**Comment by bramus** [comment]
Hi @timmccloskey,

You have two options for this. You can [overlay an image](https://developers.google.com/maps/documentation/javascript/examples/maptype-image-overlay), or you can [overlay a tileset](https://developers.google.com/maps/documentation/javascript/examples/maptype-overlay).

For the latter you cannot use `PS_Bramus.GoogleMapsTileCutter` unfortunately, as it is designed to cut a standalone tileset.

Regards,
Bramus.
