### ISSUE TITLE
Alignement issue

### ISSUE THREAD

**Issue by denisflorkin** [bramus/photoshop-google-maps-tile-cutter#15]
Hello, first of all, thanks for the script it's going to save me a lot of time.
That said I'm having an issue regarding alignement.
I align my image within a square canvas in PS, launch the script, and every time, something happen that make all the works I spent on alignement go to trash.
I don't get what or how this is happening.
It's like the script/Ps is trying to center my image in the canvas or something.

Does anyone understand what I mean ? How could I go about counteracting this issue.

The process I go use : 
 * Get a screenshot of an existing "full maps"
![screen shot 2016-11-21 at 10 43 25](https://cloud.githubusercontent.com/assets/10850995/20478611/22e425c4-afdb-11e6-8179-13658b6c1a4a.png)

 * Align my map based on that "full map screenshot" in a square canvas in PS
![screen shot 2016-11-21 at 11 11 47](https://cloud.githubusercontent.com/assets/10850995/20478679/5f65df74-afdb-11e6-8dc6-15e21835be89.png)
 * launch the script

 * at the end I end up with Ps in this state (map has been moved "somehow") : 
![screen shot 2016-11-21 at 11 13 10](https://cloud.githubusercontent.com/assets/10850995/20478716/893b6d14-afdb-11e6-8130-12f5c6ee3ba9.png)

 * and the exemple looks like this in the browser (with repeatOnXAxis = true;): 
![screen shot 2016-11-21 at 11 03 54](https://cloud.githubusercontent.com/assets/10850995/20478734/a55ddd7e-afdb-11e6-8293-f6ff18d69ede.png)

What I expect is the repeating map on x axis to be next to each other, not appart with a big space in between.

**Comment by bramus** [comment]
Hi @denisflorkin,

The size of one tile (by default) is `265x265` pixels. The entire canvas size for each zoom level is based up on this tilesize:

- For the first zoom level (which is a `2x2` tileset), the entire canvas size should be `512x512` pixels.
- For the second zoom level (which is a `4x4` tileset), the entire canvas size should be `1024x1024` pixels.
- For the third zoom level (which is a `8x8` tileset), the entire canvas size should be `2048x2048` pixels.
- For the fourth …

_(The general formula to calculate one side for a given zoom level is: `(zoomLevel ^ 2) * 256`)_

The script starts by resizing the given image to one of these dimensions. To prevent a resize make sure the width and height of your base image are one of these calculated sizes _(e.g. 512, 1024, 2048, 4096, …)_

Regards,
Bramus.

**Comment by denisflorkin** [comment]
Hi @bramus 
Thank you for the quick response, as soon as I read your explanation, the problem I had was solved. But then it was time to leave, and I did not take the time to respond.
Anyway thanks a lot the work on this repo, it just made my (yester)day!

**Comment by bramus** [comment]
Glad to have been of help :)
