### ISSUE TITLE
Missing tiles in the tilecutter folder after running script.

### ISSUE THREAD

**Issue by jacobraccuia** [bramus/photoshop-google-maps-tile-cutter#4]
I'm running Photoshop CS6 and using the tilecutter script to cut up a file that is approximately 5000 x 5000.

My script to display the image with the API seems to work perfectly, except I get image errors that some don't exist.

![screen shot 2013-09-11 at 6 16 43 pm](https://f.cloud.github.com/assets/4655860/1127054/ddaa693e-1b2f-11e3-805d-c4bb3f0a39d3.png)

I am not sure what the problem is, but I'm reporting it as an issue because I presume they should exist!

Thanks so much,
Jacob

**Comment by bramus** [comment]
Hi Jacob,

Can you upload the original image somewhere so I can try to reproduce the problem?

Regards,
Bram.

**Comment by jacobraccuia** [comment]
Hi!

I'm working on that as we speak.  You gave me the idea of trying to use a non-saved-for-web jpg instead of the saved for web one.

It was originally a PDF, which I dragged into photoshop, enlarged to 5000x5000 from ~ 2500 and then made square, and then spliced.

I will provide you with the link after I try this.  Maybe something I just said could trigger a clue?

thanks so much for the quick reply!
Jacob

**Comment by jacobraccuia** [comment]
I just went from ~ 580 images to ~1300.  I think the saved for web messed it up or something.  I will know soon if it's correct!

Confirmed - this worked!  Sorry for the non-issue, but I think information on the proper way to save the files might be useful.  Thanks!
