### ISSUE TITLE
targetPath variable has a quote error

### ISSUE THREAD

**Issue by tilmau** [bramus/photoshop-google-maps-tile-cutter#5]
the targetPath string isn't being set corretly. Instead, the path includes an unexpected single quote after the folder name. For example, if a path of ...\Desktop\tilecutter\ is being set, files are being saved like ...\Desktop\tilecutter'6_3_2.png

**Comment by bramus** [comment]
Hi @tilmau, thanks for filing this issue. 
Should be fixed by now. Can you tell me it works properly indeed?

Regards,
Bram.

**Comment by tilmau** [comment]
I will absolutely, as soon as I get around to it at work next week.
